export const specialCards = {
  uranium: {
    name: "Uranium",
    specialType: true,
    symbol: "☢️",
    atomicNumber: 92,
    atomicRadius: 230,
    electronegativity: 1.38,
  },
  flip: {
    name: "FLIP",
    specialType: true,
    symbol: "🔄",
    atomicNumber: "N/A",
    atomicRadius: "N/A",
    electronegativity: "N/A",
  },
};

export const elementalCards = [
  {
    name: "Hydrogen",
    symbol: "H",
    atomicNumber: 1,
    atomicRadius: 53,
    electronegativity: 2.2,
  },
  {
    name: "Helium",
    symbol: "He",
    atomicNumber: 2,
    atomicRadius: 31,
    electronegativity: 0,
  },
  {
    name: "Lithium",
    symbol: "Li",
    atomicNumber: 3,
    atomicRadius: 167,
    electronegativity: 0.98,
  },
  {
    name: "Beryllium",
    symbol: "Be",
    atomicNumber: 4,
    atomicRadius: 112,
    electronegativity: 1.57,
  },
  {
    name: "Boron",
    symbol: "B",
    atomicNumber: 5,
    atomicRadius: 87,
    electronegativity: 2.04,
  },
  {
    name: "Carbon",
    symbol: "C",
    atomicNumber: 6,
    atomicRadius: 67,
    electronegativity: 2.55,
  },
  {
    name: "Nitrogen",
    symbol: "N",
    atomicNumber: 7,
    atomicRadius: 56,
    electronegativity: 3.04,
  },
  {
    name: "Oxygen",
    symbol: "O",
    atomicNumber: 8,
    atomicRadius: 48,
    electronegativity: 3.44,
  },
  {
    name: "Fluorine",
    symbol: "F",
    atomicNumber: 9,
    atomicRadius: 42,
    electronegativity: 3.98,
  },
  {
    name: "Neon",
    symbol: "Ne",
    atomicNumber: 10,
    atomicRadius: 38,
    electronegativity: 0,
  },
  {
    name: "Sodium",
    symbol: "Na",
    atomicNumber: 11,
    atomicRadius: 190,
    electronegativity: 0.93,
  },
  {
    name: "Magnesium",
    symbol: "Mg",
    atomicNumber: 12,
    atomicRadius: 145,
    electronegativity: 1.31,
  },
  {
    name: "Aluminum",
    symbol: "Al",
    atomicNumber: 13,
    atomicRadius: 118,
    electronegativity: 1.61,
  },
  {
    name: "Silicon",
    symbol: "Si",
    atomicNumber: 14,
    atomicRadius: 111,
    electronegativity: 1.9,
  },
  {
    name: "Phosphorus",
    symbol: "P",
    atomicNumber: 15,
    atomicRadius: 98,
    electronegativity: 2.19,
  },
  {
    name: "Sulfur",
    symbol: "S",
    atomicNumber: 16,
    atomicRadius: 87,
    electronegativity: 2.58,
  },
  {
    name: "Chlorine",
    symbol: "Cl",
    atomicNumber: 17,
    atomicRadius: 79,
    electronegativity: 3.16,
  },
  {
    name: "Argon",
    symbol: "Ar",
    atomicNumber: 18,
    atomicRadius: 71,
    electronegativity: 0,
  },
  {
    name: "Potassium",
    symbol: "K",
    atomicNumber: 19,
    atomicRadius: 243,
    electronegativity: 0.82,
  },
  {
    name: "Calcium",
    symbol: "Ca",
    atomicNumber: 20,
    atomicRadius: 194,
    electronegativity: 1,
  },
  {
    name: "Scandium",
    symbol: "Sc",
    atomicNumber: 21,
    atomicRadius: 184,
    electronegativity: 1.36,
  },
  {
    name: "Titanium",
    symbol: "Ti",
    atomicNumber: 22,
    atomicRadius: 176,
    electronegativity: 1.54,
  },
  {
    name: "Vanadium",
    symbol: "V",
    atomicNumber: 23,
    atomicRadius: 171,
    electronegativity: 1.63,
  },
  {
    name: "Chromium",
    symbol: "Cr",
    atomicNumber: 24,
    atomicRadius: 166,
    electronegativity: 1.66,
  },
  {
    name: "Manganese",
    symbol: "Mn",
    atomicNumber: 25,
    atomicRadius: 161,
    electronegativity: 1.55,
  },
  {
    name: "Iron",
    symbol: "Fe",
    atomicNumber: 26,
    atomicRadius: 156,
    electronegativity: 1.83,
  },
  {
    name: "Cobalt",
    symbol: "Co",
    atomicNumber: 27,
    atomicRadius: 152,
    electronegativity: 1.88,
  },
  {
    name: "Nickel",
    symbol: "Ni",
    atomicNumber: 28,
    atomicRadius: 149,
    electronegativity: 1.91,
  },
  {
    name: "Copper",
    symbol: "Cu",
    atomicNumber: 29,
    atomicRadius: 145,
    electronegativity: 1.9,
  },
  {
    name: "Zinc",
    symbol: "Zn",
    atomicNumber: 30,
    atomicRadius: 142,
    electronegativity: 1.65,
  },
  {
    name: "Gallium",
    symbol: "Ga",
    atomicNumber: 31,
    atomicRadius: 136,
    electronegativity: 1.81,
  },
  {
    name: "Germanium",
    symbol: "Ge",
    atomicNumber: 32,
    atomicRadius: 125,
    electronegativity: 2.01,
  },
  {
    name: "Arsenic",
    symbol: "As",
    atomicNumber: 33,
    atomicRadius: 114,
    electronegativity: 2.18,
  },
  {
    name: "Selenium",
    symbol: "Se",
    atomicNumber: 34,
    atomicRadius: 103,
    electronegativity: 2.55,
  },
  {
    name: "Bromine",
    symbol: "Br",
    atomicNumber: 35,
    atomicRadius: 94,
    electronegativity: 2.96,
  },
  {
    name: "Krypton",
    symbol: "Kr",
    atomicNumber: 36,
    atomicRadius: 88,
    electronegativity: 0,
  },
  {
    name: "Rubidium",
    symbol: "Rb",
    atomicNumber: 37,
    atomicRadius: 265,
    electronegativity: 0.82,
  },
  {
    name: "Strontium",
    symbol: "Sr",
    atomicNumber: 38,
    atomicRadius: 219,
    electronegativity: 0.95,
  },
  {
    name: "Yttrium",
    symbol: "Y",
    atomicNumber: 39,
    atomicRadius: 212,
    electronegativity: 1.22,
  },
  {
    name: "Zirconium",
    symbol: "Zr",
    atomicNumber: 40,
    atomicRadius: 206,
    electronegativity: 1.33,
  },
  {
    name: "Niobium",
    symbol: "Nb",
    atomicNumber: 41,
    atomicRadius: 198,
    electronegativity: 1.6,
  },
  {
    name: "Molybdenum",
    symbol: "Mo",
    atomicNumber: 42,
    atomicRadius: 190,
    electronegativity: 2.16,
  },
  {
    name: "Technetium",
    symbol: "Tc",
    atomicNumber: 43,
    atomicRadius: 183,
    electronegativity: 1.9,
  },
  {
    name: "Ruthenium",
    symbol: "Ru",
    atomicNumber: 44,
    atomicRadius: 178,
    electronegativity: 2.2,
  },
  {
    name: "Rhodium",
    symbol: "Rh",
    atomicNumber: 45,
    atomicRadius: 173,
    electronegativity: 2.28,
  },
  {
    name: "Palladium",
    symbol: "Pd",
    atomicNumber: 46,
    atomicRadius: 169,
    electronegativity: 2.2,
  },
  {
    name: "Silver",
    symbol: "Ag",
    atomicNumber: 47,
    atomicRadius: 165,
    electronegativity: 1.93,
  },
  {
    name: "Cadmium",
    symbol: "Cd",
    atomicNumber: 48,
    atomicRadius: 161,
    electronegativity: 1.69,
  },
  {
    name: "Indium",
    symbol: "In",
    atomicNumber: 49,
    atomicRadius: 156,
    electronegativity: 1.78,
  },
  {
    name: "Tin",
    symbol: "Sn",
    atomicNumber: 50,
    atomicRadius: 145,
    electronegativity: 1.96,
  },
  {
    name: "Antimony",
    symbol: "Sb",
    atomicNumber: 51,
    atomicRadius: 133,
    electronegativity: 2.05,
  },
  {
    name: "Tellurium",
    symbol: "Te",
    atomicNumber: 52,
    atomicRadius: 123,
    electronegativity: 2.1,
  },
  {
    name: "Iodine",
    symbol: "I",
    atomicNumber: 53,
    atomicRadius: 115,
    electronegativity: 2.66,
  },
  {
    name: "Xenon",
    symbol: "Xe",
    atomicNumber: 54,
    atomicRadius: 108,
    electronegativity: 2.6,
  },
];
